// The update log on the website (the "Updates" page). Every update gets its own
// name. Newest first. Add a new one at the top whenever an update ships; staff can
// also post updates from the website (those are kept in the server's database).
//
//   id     short and unique (letters, numbers, dashes)
//   name   the update's name: make it fun and about what changed
//   time   when it came out (seconds since 1970, like everything else on the server)
//   tag    what it's mostly about: Engine, Studio, Website, Player, Server, Fix
//   items  what changed, one short line each, in plain words

export const BUILT_IN_UPDATES = [
  {
    id: 'robot-qa-department', name: 'We Hired Robots to Break Things', time: 1791347000, tag: 'Server',
    summary: 'Automatic tests now check the website\'s server every time something changes.',
    items: [
      'Signing up, the daily Bolts, buying items, comments, the filter and staff tools are all tested automatically',
      'The update log, the "Library" wording and the C++ filter\'s word list are checked too',
      'Every website script is checked for typing mistakes before it goes live',
    ],
  },
  {
    id: 'the-save-button-works-now', name: 'The Save Button Works Now', time: 1791346000, tag: 'Fix',
    summary: 'Saving an item\'s Edit box (like making it a timed item) works again, and the useless colour box is gone.',
    items: [
      'Saving changes to an item no longer fails with "That wasn\'t a proper request"',
      'Making an item a timed item saves properly, and a half-typed date now says what to fix',
      'Removed the Colour box from editing items, since it didn\'t do anything',
    ],
  },
  {
    id: 'receipts-please', name: 'Receipts, Please', time: 1791345500, tag: 'Server',
    summary: 'A staff action log: every ban, warning, badge and delete is written down.',
    items: [
      'The Staff page shows what staff did lately, and who did it',
      'Bans, warnings, badges, Bolts, upload checks, closed reports and deletes all go in it',
      'A Log button next to each person shows just what happened to them',
    ],
  },
  {
    id: 'peanut-gallery', name: 'The Peanut Gallery', time: 1791345000, tag: 'Website',
    summary: 'Comments under games: tell a creator what you think of their game.',
    items: [
      'Every game page has comments now, on the website and in the app',
      'Delete your own comments; creators can delete any on their game, or turn comments off',
      'Report a comment if it breaks the rules, and creators get a notification for new ones',
    ],
  },
  {
    id: 'number-go-up', name: 'Number Go Up', time: 1791343500, tag: 'Website',
    summary: 'Creator stats: see how your games and items are doing, day by day.',
    items: [
      'New Stats tab on the Create page, on the website and in the app',
      'Plays, people playing now, favorites, likes, sales and Bolts earned for everything you made',
      'Little bar charts for the last 30 days (hover a bar to see the day)',
      'Passes and products bought inside a game count toward that game',
    ],
  },
  {
    id: 'cha-ching-forever', name: 'Cha-Ching Forever', time: 1791342000, tag: 'Engine',
    summary: 'Developer products: sell things inside your game that players can buy again and again, like coins or a revive.',
    items: [
      'Make them on your game\'s Configure page, then pop up a Buy window with MarketplaceService:PromptProductPurchase',
      'MarketplaceService.ProcessReceipt hands out what they bought, like on Roblox',
      'Every purchase is kept until the game says it handed it out, so nobody loses what they paid for',
      'You get 70% of every sale',
    ],
  },
  {
    id: 'we-outsourced-the-update', name: 'We Outsourced the Update', version: '0.7.0', time: 1791341100, tag: 'Engine',
    summary: 'An AI wrote most of this one: smarter AI helpers, teleporting between games, a chat filter, upload checks and a notification bell.',
    items: [
      'AI helpers (the Assistant tab, and MCP apps like Claude) now really know how Guts&Bolts works and check their own work',
      'New AI tools for physics, explosions, the navmesh, walking characters, watching the game, and save points',
      'TeleportService: send players to another game, with data, like Roblox',
      'The website\'s Play button opens the Player on a Mac too',
      'A text filter: slurs, links and personal info become [ Content Deleted ]',
      'New decals, sounds and T-shirts wait for a staff check (Verified creators skip the line)',
      'A notification bell for friend requests, sales, trades, groups and upload checks',
    ],
  },
  {
    id: 'ding-dong-ditch', name: 'Ding Dong Ditch', version: '0.7.0', time: 1791341000, tag: 'Website',
    summary: 'A notification bell: see friend requests, sales, trades, group news and upload checks in one place.',
    items: [
      'A bell next to your name on the website and in the Player, with a red number for new things',
      'Friend requests, new friends and followers, sales, trades and group requests all ring it',
      'You also hear back when staff check something you uploaded (and why, if it was turned down)',
      'Click one to go straight to that page',
    ],
  },
  {
    id: 'bouncer-at-the-door', name: 'Bouncer at the Door', version: '0.7.0', time: 1791340000, tag: 'Server',
    summary: 'New decals, sounds and T-shirts from creators who aren\'t Verified wait for a staff check before anyone else sees them.',
    items: [
      'Until staff OK it, only you can see or hear your new upload, and its page says it\'s waiting',
      'Staff get an "Uploads to check" list on the Staff page, on the website and in the Player',
      'Uploads that get turned down say why, so you know what to fix',
      'Verified creators skip the line',
    ],
  },
  {
    id: 'robot-brain-transplant', name: 'Robot Brain Transplant', version: '0.7.0', time: 1791339011, tag: 'Studio',
    summary: 'AI helpers (the Assistant tab and MCP apps like Claude) now really understand Studio: they look before they touch, check their work, and stop making things up.',
    items: [
      'A brand new guide that teaches any AI how Guts&Bolts works and how to use its tools safely',
      'Every AI tool explains when to use it, when not to, what it needs and what it gives back',
      'Tools answer with exact data (ids, positions, what really changed) and clear error codes with what to try next',
      'New tools: find_objects, get_errors, diagnose_object ("why won\'t my barrel fall?") and validate_scene',
      'Script changes are checked for Lua mistakes straight away',
      'Delete is marked as risky, so AIs only delete what you clearly asked for',
      'AIs can read how the engine works: what it can and can\'t do, its words for things, which way is up, and step-by-step recipes',
      'Every object is picked by its id (#42); if a name is used twice, the AI is asked which one instead of guessing',
      'Power tools for AIs: make a physics object in one go, set off explosions, bake the navmesh, find walking routes and send characters walking',
      'AIs can watch the running game (frame rate, what\'s moving, where characters are) and pause or step it',
      'Save points: an AI can save the game, try something wild, and roll back if it goes wrong (plus redo)',
    ],
  },
  {
    id: 'soap-in-the-mouth', name: 'Soap in the Mouth', version: '0.7.0', time: 1791330000, tag: 'Server',
    summary: 'A text filter: anything with slurs, links or personal info in it becomes [ Content Deleted ], like classic Roblox.',
    items: [
      'Chat, messages, profiles, group posts and the names and descriptions of things are all filtered',
      'Slurs are caught even with spaces, dots or look-alike letters in them',
      'Links (except to gutsandbolts.net), email addresses and phone numbers are covered so nobody shares personal info',
      'Usernames and guest names with slurs in them aren\'t allowed',
    ],
  },
  {
    id: 'apple-of-my-eye', name: 'Apple of My Eye', version: '0.7.0', time: 1791328060, tag: 'Player',
    summary: 'The website\'s Play button opens the Player on a Mac too, not just on Windows, Linux and Android.',
    items: [
      'Open the Player once on your Mac, and Play and Join on the website open it straight into the game',
      'It adds a small Guts&Bolts Player app to your Applications folder, which macOS needs for links',
      'If the Player is already open, the link goes to it instead of opening another one',
      '"Edit in Studio" links work on a Mac the same way',
    ],
  },
  {
    id: 'portal-hopper', name: 'Portal Hopper', version: '0.7.0', time: 1791327890, tag: 'Engine',
    summary: 'TeleportService: games can send players to another game, and bring some data along, like Roblox.',
    items: [
      'TeleportService:Teleport and TeleportAsync send one player or a whole group to another game by its ID',
      'Send data with them (TeleportOptions:SetTeleportData), and read it there with player:GetJoinData()',
      'Players land in an open server of that game, or a new one if none is open',
      'Works from game server machines, from whoever is hosting, and from LocalScripts for your own player',
      'In Studio\'s play test, Output says where a player would have gone',
    ],
  },
  {
    id: 'total-goblin-mode', name: 'Total Goblin Mode', version: '0.6.9', time: 1791326339, tag: 'Engine',
    summary: 'The biggest drop yet: servers that run with nobody hosting, LocalScripts, controllers, glowing trails, and a hammer for creators.',
    items: [
      'Games can run on game server machines, so nobody gets kicked when the host leaves',
      'LocalScripts, RemoteEvents and RemoteFunctions, like Roblox',
      'Everyone can carry tools, and saved data follows players to every server',
      'Text boxes, scrolling lists, floating signs and screens on walls',
      'ProximityPrompts, Highlights, Trails and Beams',
      'Play with a controller',
      'Report and block people, on the website and in the app',
      'A hammer next to the game creator on the leaderboard, and require(ID) in the server dev console',
    ],
  },
  {
    id: 'hammer-time', name: 'Hammer Time', version: '0.6.9', time: 1791325965, tag: 'Player',
    summary: 'Game creators get a hammer on the leaderboard, and the server dev console can require modules.',
    items: [
      'A little hammer shows next to the game creator\'s name on the leaderboard',
      'require works in the server side of the dev console, even for modules that wait() while they start',
      'require(ID) loads a model from the Library and runs its MainModule, like Roblox (server only)',
      'The server side of the dev console stays for the game\'s creator only, now in solo play too',
    ],
  },
  {
    id: 'pick-up-and-play', name: 'Pick Up and Play', version: '0.6.9', time: 1791325100, tag: 'Player',
    summary: 'Controller support: play any game with an Xbox, PlayStation or Switch controller.',
    items: [
      'Walk with the left stick, look around with the right one, jump with A',
      'RT uses your tool, LB and RB switch tools, X presses the prompt you are next to',
      'Start opens the menu, and the D-pad and A move around it and the Player\'s pages',
      'Works in Studio\'s play test too',
      'Scripts can read controller buttons and sticks, like Roblox (ButtonA, GamepadEnabled...)',
    ],
  },
  {
    id: 'light-streaks', name: 'Light Streaks', version: '0.6.9', time: 1791324400, tag: 'Engine',
    summary: 'Trails and Beams: swords leave streaks behind them, and lasers join two points, like Roblox.',
    items: [
      'A Trail leaves a fading ribbon behind two Attachments as they move',
      'A Beam joins two Attachments with a ribbon that can curve, glow and scroll a picture',
      'ColorSequence and NumberSequence let colours, see-through and width change along them',
      'Add them in Studio from Insert Object, with their settings in Properties',
      'They show for everyone in multiplayer, and Roblox games with them now import with them',
    ],
  },
  {
    id: 'glow-up', name: 'Glow Up', version: '0.6.9', time: 1791323500, tag: 'Engine',
    summary: 'Highlights: colour a part or a whole character and give it an outline, even through walls, like Roblox.',
    items: [
      'Put a Highlight in a part or model and it gets a coloured fill and an outline',
      'AlwaysOnTop shows it through walls; Occluded only where you can see it',
      'Pick the fill and outline colours and how see-through each one is',
      'Highlights the server puts on players show for everyone in multiplayer',
      'Roblox games with Highlights now import with them',
    ],
  },
  {
    id: 'press-e', name: 'Press E', version: '0.6.9', time: 1791322400, tag: 'Engine',
    summary: 'ProximityPrompts: walk up to a door and a little "E Open" card pops up, like Roblox.',
    items: [
      'Put a ProximityPrompt in a part, and players near it see a card with the key to press',
      'Pressing the key, or clicking or tapping the card, fires Triggered with the player who did it',
      'HoldDuration makes players hold the key while a ring fills up',
      'Works for everyone in multiplayer games, and the server checks they are really close',
      'Roblox games with ProximityPrompts now import with them working',
    ],
  },
  {
    id: 'pass-the-note', name: 'Pass the Note', version: '0.6.9', time: 1791318200, tag: 'Engine',
    summary: 'LocalScripts run on each player\'s own computer now, and talk to the server with RemoteEvents, like Roblox.',
    items: [
      'LocalScripts run on the player\'s computer: great for UI, keys and things only you see',
      'RemoteEvents send messages between LocalScripts and Scripts (FireServer, FireClient, FireAllClients)',
      'RemoteFunctions ask the server a question and wait for the answer (InvokeServer)',
      'Players who join no longer get the code inside your server Scripts',
      'Roblox games with LocalScripts and RemoteEvents now import with them working',
    ],
  },
  {
    id: 'signs-everywhere', name: 'Signs Everywhere', version: '0.6.9', time: 1791314600, tag: 'Engine',
    summary: 'Game UI can sit on parts now: floating name signs (BillboardGui) and screens painted on walls (SurfaceGui).',
    items: [
      'BillboardGui floats over a part and always faces you, for name signs, health bars and hints',
      'SurfaceGui paints labels, pictures and buttons on one side of a part, and you can click its buttons',
      'Both hide when something is in front of them, unless you tick AlwaysOnTop',
      'Insert them on a part in Studio, or make them in scripts with the same names as Roblox',
      'Roblox files with BillboardGuis and SurfaceGuis now import instead of losing them',
    ],
  },
  {
    id: 'type-and-scroll', name: 'Type and Scroll', version: '0.6.9', time: 1791311000, tag: 'Engine',
    summary: 'Game UI gets text boxes, scrolling lists and automatic layouts, like Roblox.',
    items: [
      'TextBox: players can type in your game. FocusLost tells your script when they press Enter',
      'ScrollingFrame: lists longer than the screen scroll with the mouse wheel, the scroll bar or a finger',
      'UIListLayout and UIGridLayout line things up for you, so shops and inventories are easy to build',
      'UIPadding keeps things away from the edges, and LayoutOrder picks what comes first',
      'Works for players who joined someone else\'s game too, and in Roblox files you import or export',
    ],
  },
  {
    id: 'shared-vault', name: 'Shared Vault', version: '0.6.9', time: 1791307400, tag: 'Server',
    summary: 'Saved game data (DataStores) now lives on the Guts&Bolts server, so it follows players to every server of a game.',
    items: [
      'DataStoreService saves online when the game runs on a game server machine or its creator hosts it',
      'Coins, levels and anything else saved in one server are there when you join another',
      'IncrementAsync adds on the server in one step, so two servers adding at once both count',
      'Other people hosting your game, or playing a file alone, still save on their own computer, so nobody can cheat your game\'s data',
      'Limits: 256 KB per value and 100,000 keys per game',
    ],
  },
  {
    id: 'night-shift', name: 'Night Shift', version: '0.6.9', time: 1791305600, tag: 'Server',
    summary: 'Games can run on a game server machine with nobody hosting, so nobody gets kicked when someone leaves.',
    items: [
      'New program: GutsAndBoltsGameServer. Leave it running on a computer that stays on and it runs games by itself',
      'Press Play and, if no server has room, a free game server machine starts one for you. You join it a few seconds later',
      'Nobody is the host on those servers, so the game keeps going whoever leaves',
      'No screen or graphics card needed: it runs fine on a cheap Linux cloud server',
      'Empty games close after a minute. If no machine is free, the first player hosts like before',
      'Server cards show "Guts&Bolts" as the host for these servers',
    ],
  },
  {
    id: 'pass-the-bat', name: 'Pass the Bat', version: '0.6.9', time: 1791303800, tag: 'Engine',
    summary: 'People who join someone else\'s game can carry tools now, not just the host.',
    items: [
      'Everyone in an online game gets the StarterPack tools when they spawn, and again after they respawn',
      'Walk into a tool to pick it up, press 1-9 to hold one, click to swing, Backspace to drop it',
      'The tool\'s scripts run on the game\'s server, so tool.Activated, Equipped, Unequipped and Handle.Touched work for everyone',
      'You can see what everyone else is holding, and it moves with their hand',
      'Scripts can give anyone a tool (player.Backpack) and use humanoid:EquipTool on anyone',
      'Fix: putting a tool away and taking it out again no longer drops it on the ground',
    ],
  },
  {
    id: 'bouncer', name: 'The Bouncer', version: '0.6.9', time: 1791302600, tag: 'Website',
    summary: 'Report anything that breaks the rules, and block people you don\'t want to hear from. Staff get a list of reports to work through.',
    items: [
      'A Report link on profiles, messages, games, catalog items, Library items and groups. Pick what\'s wrong and tell staff what happened',
      'The person you report isn\'t told who reported them. Reporting a message sends staff a copy, so deleting it doesn\'t hide it',
      'Block someone from their profile (or tick "Block them too" when you report them)',
      'Blocking ends your friendship and follows, and you can\'t message, friend, follow, trade with or join each other. You won\'t see each other online',
      'See and unblock the people you blocked in Settings',
      'The Staff page has a Reports box: what was reported, why, a copy of reported messages, and Done / Nothing wrong buttons',
      'All of it works in the Player app too: Report and Block buttons, Blocked people under Avatar > Your account, and the Reports list on the Staff page',
      'The app\'s privacy settings can also choose who can send you messages, like the website',
    ],
  },
  {
    id: 'old-faithful', name: 'Old Faithful', version: '0.6.8', time: 1791295000, tag: 'Engine',
    summary: 'The classic BodyMovers are back next to the newer movers, so old vehicles and flying keep their handling. And you can sit down anywhere.',
    items: [
      'Classic BodyMovers: BodyVelocity, BodyPosition, BodyGyro, BodyAngularVelocity, BodyThrust and BodyForce. Put one in an unanchored part',
      'Newer mover constraints too: LinearVelocity, AlignPosition, AlignOrientation, AngularVelocity, VectorForce and Torque (they push through an Attachment)',
      'They push the whole welded build, so cars, planes and hoverboards move as one',
      'They work on characters as well (flying scripts with a BodyVelocity and BodyGyro in the Torso)',
      'Old games keep working: Roblox files bring their movers in with the right speeds and forces, and old lower-case names like bv.velocity still work',
      'New part:GetMass() and part.AssemblyMass for working out forces',
      'Sit anywhere: Humanoid.Sit = true (or type /e sit) sits you down right where you stand, no seat needed. Jump to get up',
    ],
  },
  {
    id: 'frosted-glass', name: 'Frosted Glass', time: 1791290000, tag: 'Engine',
    summary: 'Game UI gets soft drop shadows, a real see-through blur, corners you can round one at a time, and games can use an orthographic camera.',
    items: [
      'New UIShadow: put it in a Frame, label or button for a soft shadow under it (Color, Transparency, Offset, Blur, Spread)',
      'New UIBlur: the world behind a Frame turns into frosted glass (Size sets how blurry). It\'s done on the graphics card, no pictures needed',
      'UICorner can round each corner on its own: TopLeft, TopRight, BottomRight, BottomLeft (0 = a sharp corner)',
      'Orthographic camera: no perspective, so far things aren\'t smaller. Great for 2D, isometric and puzzle games',
      'Turn it on in Studio\'s Player tab (Camera), or in scripts: workspace.Orthographic = true and workspace.OrthographicSize = 40',
      'Studio\'s view can go orthographic too: the Ortho button on the Home tab, or numpad 5 like Blender',
    ],
  },
  {
    id: 'fast-pass', name: 'Fast Pass', time: 1791286900, tag: 'Website',
    summary: 'Game passes: creators sell perks for their games, and players buy them on the game page or right inside the game.',
    items: [
      'Make passes for your game on its Configure page on the website: a name, a description, a price in Bolts and a picture',
      'Passes show on the game\'s page (website and Player) with a Buy button; creators get 70% of every sale',
      'Scripts check them like Roblox: MarketplaceService:UserOwnsGamePassAsync(player.UserId, passId)',
      'MarketplaceService:PromptGamePassPurchase(player, passId) pops up a Buy window in the game, and PromptGamePassPurchaseFinished says how it went',
      'Selling passes for Bolts needs a Verified account (free passes are for everyone)',
    ],
  },
  {
    id: 'mill-race', name: 'Mill Race', time: 1791286800, tag: 'Engine',
    summary: 'Water pushes things the way it should, so a river turns a water wheel. Studio\'s right-click menu got a lot bigger.',
    items: [
      'Water pushes hard on flat sides moving through it (or facing a current) and hardly at all on edges, like a paddle',
      'A new Water Wheel in the Toolbox: put it in, press Play and the river turns it. Change the river\'s Flow to speed it up',
      'Water parts have a Drag setting: 1 is water, 5 is like mud, 0 lets things through (FluidVolume.Drag in scripts)',
      'Studio: right-click in the Explorer or the 3D view to cut, copy, paste, group, union, select, zoom to, anchor, lock, export or publish',
    ],
  },
  {
    id: 'window-shopping', name: 'Window Shopping', version: '0.6.7', time: 1791249962, tag: 'Studio',
    summary: 'The Catalog and Library look like the old catalog, gear is held the classic way, and Studio can publish models and animations from a right-click.',
    items: [
      'Catalog and Library (website and Player): a search bar with a category box, Browse by Category down the left, Price and Creators filters, Sort by, and a little info box when you point at an item',
      'The Library has a new Animations section',
      'Gear is held like classic Roblox: arm straight out, the sword pointing up',
      'Studio: right-click what you selected (in the Explorer or the 3D view) and pick Publish to Guts&Bolts to share it as a public or private model',
      'Animation Editor: a "..." menu like Roblox\'s (Load, Save, Save As, Import, Export, Create New, Set Animation Priority), Roblox-style play buttons, and Space plays or pauses',
      'Publish animations to Guts&Bolts as public (other creators can use them) or private (only you), and import them back by ID',
      'Studio\'s Explorer shows Roblox\'s services (ReplicatedStorage, ServerScriptService, StarterPack and more); game:GetService knows them too',
      'The website\'s My Games has an Edit in Studio button that opens your game straight in Studio',
      'Fixed: an error on the Player\'s Create > Library page',
    ],
  },
  {
    id: 'home-delivery', name: 'Home Delivery', version: '0.6.6', time: 1791248400, tag: 'Website',
    summary: 'Download Guts&Bolts straight from gutsandbolts.net, and it updates itself from there too.',
    items: [
      'The Download buttons on gutsandbolts.net give you the Player and Studio (and the Android app) directly',
      'The apps update themselves from gutsandbolts.net: they download the new version and restart, and your own games stay put',
    ],
  },
  {
    id: 'paint-job', name: 'Paint Job', version: '0.6.6', time: 1791244800, tag: 'Studio',
    summary: 'Hats imported from Roblox files show their pictures for everyone, on the website too.',
    items: [
      'Some hats still used a picture that only lived on the computer that made them, so the website (and everyone else) saw them plain white',
      'Studio: File > Upload Missing Item Pictures finds your hats and gear like that, uploads their pictures and fixes them in one go',
      'New hats and gear upload their pictures by themselves when you publish them',
    ],
  },
  {
    id: 'new-address', name: 'Moving Day', version: '0.6.6', time: 1791241500, tag: 'Website',
    summary: 'Guts&Bolts has its own address now: gutsandbolts.net.',
    items: [
      'The website lives at gutsandbolts.net (www.gutsandbolts.net works too)',
      'The Player and Studio connect to gutsandbolts.net from the next update on',
      'The old address keeps working for the apps, so nobody gets cut off while they update. Opening it in a browser takes you to gutsandbolts.net',
    ],
  },
  {
    id: 'peek-under-the-hood', name: 'Peek Under the Hood', version: '0.6.5', time: 1791240600, tag: 'Player',
    summary: 'The Developer Console, like Roblox: press F9 or type /devconsole in a game.',
    items: [
      'Client tab: everything that happened on your computer, errors in red and warnings in yellow, with a search box',
      'Server tab, only for the game\'s owner: the server\'s log (what your scripts print) and a command bar that runs Lua on the server',
      'Other players never get the Server tab, so only you can poke at your game while it runs',
    ],
  },
  {
    id: 'nobody-gets-left-behind', name: 'Nobody Gets Left Behind', version: '0.6.5', time: 1791240300, tag: 'Server',
    summary: 'When the player hosting a game leaves, everyone else moves to a new server together instead of getting kicked.',
    items: [
      'Before: if the first person in a server left, everyone else got thrown back to the home screen',
      'Now: the player who has been there longest starts a new server of the same game, and everyone follows them there by themselves',
      'Private servers keep the same code, so friends can still join with it',
      'You see "The host left. Moving everyone to a new server" for a few seconds, then you\'re back in (the world starts fresh)',
    ],
  },
  {
    id: 'cut-and-paste-studio', name: 'Studio Gets Its Hands Dirty', version: '0.6.5', time: 1791244800, tag: 'Studio',
    summary: 'Unions, Roblox-style Move and Scale handles, box select, blue selection boxes, Script Analysis and AutoSave.',
    items: [
      'Unions like Roblox: Union (Ctrl+Shift+G) joins parts into one, Negate (Ctrl+Shift+N) turns a part into a hole that gets cut out, Intersect (Ctrl+Shift+I) keeps the overlap, Separate (Ctrl+Shift+U) gives the parts back',
      'Scale has an orb on each of the 6 sides: drag one to move just that side (hold Ctrl for both sides)',
      'Move has an arrow on each side, and moves everything you selected (with snapping and collisions)',
      'Rotating several things now turns them all together instead of only the last one picked',
      'Click empty space and drag to box-select parts',
      'Selected parts get a light blue box around them',
      'Script Analysis (VIEW tab): finds mistakes in every script without pressing Play, like a missing "end" or a misspelled name',
      'AutoSave: unsaved work is backed up every 5 minutes, and Studio offers to bring it back after a crash',
    ],
  },
  {
    id: 'gear-up-look-it-up', name: 'Gear Up, Look It Up', version: '0.6.5', time: 1791158400, tag: 'Studio',
    summary: 'Every Library asset gets its own page you can find by ID, and Guts can make gear straight from Studio.',
    items: [
      'Asset pages: every decal, sound, model and plugin in the Library has its own page, found by its ID',
      'Listen to audio right on its page, see decals full size, and press Copy ID to paste it into your game',
      'Got an ID? Paste it into the box on the Library page to jump straight to it (website and Player)',
      'Every asset now has a plain number for its ID, counting up like Roblox (1, 2, 3...). Type it straight into a Decal\'s Texture or a Sound\'s SoundId. Old IDs keep working',
      'The Player app has a Library tab on its Create page with the same pages',
      'Studio: File > Make Gear for staff. Start from a Classic Sword, Rocket Launcher, Speed Coil, Gravity Coil or Bomb, try it, then sell it',
      'The ready-made gear is in the Toolbox for everyone to use in their own games',
      'Fixed: hats with a picture (like imported Roblox hats) now show it on the website too. Studio uploads the picture with the hat now, so upload older textured hats again',
    ],
  },
  {
    id: 'right-now-im', name: 'Right Now I\'m...', version: '0.6.5', time: 1790899200, tag: 'Website',
    summary: 'Classic profile stuff: an About me, a "Right now I\'m..." status, My Feed on the home page and Player Badges you earn on your own.',
    items: [
      'About me: write a few lines about yourself on your profile (press Edit under the About box)',
      'Right now I\'m...: a short status (up to 140 letters) that shows on your profile',
      'My Feed on the home page: your status and your friends\' and the people you follow, newest first',
      'Player Badges: earned by themselves when you make a game (Creator), get 100 visits (Builder) or 1,000 (Architect), have 20 friends (Friendly), own 10 catalog items (Collector) or stay a year (Old Timer)',
      'Locked badges are grey; hover one to see how to get it',
      'All of it is in the Player app too, on profiles and the home page',
    ],
  },
  {
    id: 'youve-got-mail', name: 'You\'ve Got Mail', version: '0.6.5', time: 1790877600, tag: 'Player',
    summary: 'Private messages, saved outfits, favourite games and a "Continue Playing" row on the home page.',
    items: [
      'Messages: an inbox like old Roblox. Send anyone a message from their profile, reply, and see a red count when something new arrives',
      'Choose who can message you in Settings > Privacy: everyone, friends only, or no one',
      'Saved outfits: save your whole look on the Avatar page and put it back on in one click (up to 30)',
      'Favourite games with the star on a game\'s page, and find them again on the home page',
      'Continue Playing: the games you played last, right on the home page',
      'All of this is in the Player app too: a Messages page, an Outfits tab on the Avatar page, and Continue Playing and Favorites on the home page',
      'The Player dresses up for Gutstober too (orange and purple, a pumpkin and bats); turn it off in Settings',
    ],
  },
  {
    id: 'gutstober-has-risen', name: 'Gutstober Has Risen', version: '0.6.4', time: 1790869400, tag: 'Website',
    summary: 'October is Gutstober: the website dresses up for Halloween, and Gutstober items are only for sale for a limited time.',
    items: [
      'Gutstober theme on the website for all of October: orange and purple, a pumpkin and some bats',
      'Don\'t like it? Turn it off (or back on) in Settings > Site theme',
      'Timed items: an item can go off sale at a set time. You\'ll see "Off sale in 30 days" on it, then "Off sale" once it\'s over',
      'The Pumpkin hat is a Gutstober item: get it before November 1st, because then it goes off sale for good',
    ],
  },
  {
    id: 'liquid-assets-explosive-results', name: 'Liquid Assets & Explosive Results', version: '0.6.4', time: 1790868800, tag: 'Engine',
    summary: 'Explosions with real shockwaves, fire, smoke and mushroom clouds, bombs that blow holes in the water and send out tsunamis, real item pictures and friends lists you can browse.',
    items: [
      'Explosions have a shockwave that races outwards: it breaks joints, flings loose parts (light ones further), knocks people over and shakes the camera as it passes',
      'Fireballs roll up into thick smoke, fires keep burning on the ground, and big blasts make a mushroom cloud with a ring of dust rushing along the ground',
      'Bombs in or near water blow a crater in the surface, throw up a tall column of spray and send out rings of waves',
      'Big bombs in big water make a tsunami: a wall of water that rolls outwards, lifts boats, sweeps players and parts along and runs up onto the shore',
      'Scripts: Explode(position, radius, power, options) with Smoke, Fire, MushroomCloud, Destroy and more, and Instance.new("Explosion") works like Roblox (BlastRadius, BlastPressure, Hit)',
      'New premades in Studio: Time Bomb, Nuke and Depth Charge',
      'Item pictures are real renders now, never drawn icons or uploaded pictures: every catalog item is drawn from the item itself, worn by a mannequin (zoomed in on the head for hats, hair and faces) or, for gear, the tool on its own',
      'New item pages, like the 2016 catalog: a NEW ribbon, the LIMITED tag, a buy box with how many are left, a live "Offsale in 23 h 52 m" countdown for timed items, and the creator\'s character by their name',
      'Hats and accessories show up properly on characters on the website and on profiles in the Player',
      'You can look at anyone\'s Friends, Following and Followers lists, and every name is a blue link to their profile',
      'Walking up a slightly taller part is smooth now instead of snapping up in one go',
    ],
  },
  {
    id: 'who-let-us-cook', name: 'Who Let Us Cook?', version: '0.6.3', time: 1790850600, tag: 'Engine',
    summary: 'NPCs that find their own way, gear in the catalog, 2011-style moves, safer accounts and a whole lot more for creators.',
    items: [
      'Navmesh and pathfinding: Studio bakes every floor characters can walk on, and NPCs walk around walls, jump up ledges, drop down and leap gaps by themselves (PathfindingService, humanoid:PathfindTo)',
      'Gear in the catalog: buy it, equip up to 4, and bring it into games that allow gear',
      'Characters move like 2011 Roblox: the Animate script, /e dance, wave, point, laugh and cheer, PlatformStand, tripping and flinging',
      'Tools are held in the hand the Roblox way (RightGrip and Grip), so imported Roblox gear works',
      'Roblox hats come in with their real mesh and texture',
      'Studio: Roblox-style Move and Rotate increments, a studs readout by the mouse while you drag, free Blender-style moving with increments off, and right-click Insert Object in the Explorer',
      'More Lua: TweenService, workspace:Raycast, HttpService JSON, Random.new, math.noise, BindableEvent and ReplicatedStorage',
      'Your user number (like #5) is now how you find and add people: no more long account keys',
      'Leaderboard folds away with Tab or its arrow; click a name to Friend or Follow them',
      'Following, and Guts follows everybody (like Builderman did)',
      'Join buttons on profiles, plus privacy settings for who sees you online and who can join you',
      'Security: authenticator app codes when logging in, and confirming your email gives you the Verified Hat',
      'Terms of Service, and a heads-up on sign-up that Guts&Bolts is for adults (18+)',
      'Player and Studio update themselves when a new version is out',
    ],
  },
  {
    id: 'take-a-seat', name: 'Take a Seat', version: '0.6.3', time: 1790823545, tag: 'Engine',
    summary: 'Sit on seats, jump as high as a real Roblox character, and the camera stops peeking through walls.',
    items: [
      'Seats: walk into one and you sit down (like Roblox), riding along if it moves; jump to get up. Insert one from Insert Object, and Roblox Seats come in working',
      'Scripts: Humanoid.Sit, Humanoid.SeatPart, seat.Occupant, seat.Disabled and seat:Sit(humanoid)',
      'Jumps are higher: about 1.4 times your height, like Roblox. New JumpHeight and UseJumpPower settings',
      'The camera comes in front of walls instead of going through them',
      'Phones: the thumbstick stays put in the corner instead of jumping to your thumb',
      'Bans now show a ban screen (why, staff\'s note, and when it ends), bans can last 1, 3, 7 or 30 days, and staff can send warnings you have to read',
    ],
  },
  {
    id: 'dress-code', name: 'Dress Code', version: '0.6.3', time: 1790812100, tag: 'Player',
    summary: 'Get dressed right on the Avatar page, and your character finally wears its clothes everywhere.',
    items: [
      'New Wardrobe on the app\'s Avatar page: everything you own, sorted into Shirts, Pants, T-Shirts, Faces, Hats, Hair and Accessories',
      'Click something to wear it, click it again (or in the Wearing row) to take it off, or take everything off at once',
      'Fix: your character on the home screen (app and website) showed up in no clothes',
      'Friends\' little pictures on profiles wear their outfits too',
    ],
  },
  {
    id: 'hotfixes-headaches-hand-grenades', name: 'Hotfixes, Headaches & Hand Grenades', version: '0.6.2', time: 1790810194, tag: 'Studio',
    summary: 'Bring 3D models from Blender and friends into Studio, just drag files in, and catalog clothes show their real pictures.',
    items: [
      'Import 3D models: .fbx, .obj, .gltf, .glb, .stl and .ply, each object a mesh part in its own colour, all in one Model',
      'Drag files from your computer straight onto Studio: models land where you drop them, pictures stick on the part under the mouse (or stand on a sign), sounds, scripts and Roblox files work too',
      'Way too big or tiny models (like ones made in millimetres) are resized to about 10 studs',
      'Fix: shirts, pants and T-shirts in the catalog show the real clothing on the mannequin, on the website and in the app',
    ],
  },
  {
    id: 'tee-time', name: 'Tee Time', version: '0.6.2', time: 1790808000, tag: 'Website',
    summary: 'T-shirts: put any picture on the front of your character.',
    items: [
      'New T-Shirts in the catalog: any .png or .jpg, worn flat on the front of the torso (over your shirt)',
      'Make them on the Create page (website or app) and wear them from the Avatar page; the 3D avatars show them too',
      'Avatars put on on the website now show up properly in the game (clothes, faces, accessories and T-shirts)',
      'The Avatar page swaps items of the same kind instead of stacking them',
    ],
  },
  {
    id: 'riptide', name: 'Riptide', version: '0.6.2', time: 1790807100, tag: 'Engine',
    summary: 'Rivers flow around rocks, splashes leave things wet, and diving looks like diving.',
    items: [
      'Flow maps: a river\'s current splits around boulders and pillars and speeds up past them, with white water on the sides; the ripples follow it, and so do swimmers and floating things',
      'Caustics bend with the waves above them, and now light up everything underwater when you dive',
      'Cook-Torrance sun glints: blinding sparkles on wave crests facing the sun',
      'Wet things: splashes and dripping swimmers leave walls, decks and floors darker and shinier, drying over half a minute',
      'Underwater: far things go blurry, colours split a little at the edges, and water runs down the screen when you come up for air',
    ],
  },
  {
    id: 'steady-aim', name: 'Steady Aim', version: '0.6.2', time: 1790806300, tag: 'Fix',
    summary: 'The camera no longer slowly tilts up by itself in Shift Lock, first person or fullscreen.',
    items: [
      'With the mouse locked, the middle of the screen was often half a pixel, and the pointer can only sit on whole pixels, so every frame looked like a tiny mouse move up',
      'The camera now only moves when you move the mouse',
    ],
  },
  {
    id: 'deep-end', name: 'The Deep End', version: '0.6.2', time: 1790805900, tag: 'Engine',
    summary: 'Pools, lakes and rivers get real ocean waves, crystal-clear shallows and splashes that throw real water.',
    items: [
      'Gerstner waves: sharp crests and wide troughs, with whitecaps on big ones; floating things ride the exact waves you see',
      'Water fades from crystal clear at the shore to deep blue in the deep, with the new Clarity setting',
      'Things under the water are bent by it (refraction), and sunlight dances on the bottom',
      'Reflections of the world, and foam where water meets the shore',
      'Big splashes and waves slapping walls throw real liquid drops that fall back in',
      'New FluidVolume for scripts: FlowVelocity, Clarity, WaveScale, and :ParentTo()',
    ],
  },
  {
    id: 'crisp-edges', name: 'Crisp Edges', version: '0.6.2', time: 1790804476, tag: 'Fix',
    summary: 'No more flickering stripes where water touches walls.',
    items: [
      'Pools, rivers and any Water part sitting against a wall or floor no longer z-fight (the grey streaks on the walls)',
      'Looks clean from underwater too',
    ],
  },
  {
    id: 'hydromania', name: 'The Hydromania Update', version: '0.6.1', time: 1790794400, tag: 'Engine',
    summary: 'Swim, dive, float and sink. Water you can really get into, and a Render Distance bar to keep big maps smooth.',
    items: [
      'You float at the surface with your head out, bobbing with the waves',
      'Dive with C (or Ctrl), or swim forward while looking down; look up or hold Space to come back up',
      'Underwater everything goes blue and hazy, darker the deeper you go',
      'Density on every part: water is 1.3, lighter things float and heavier things sink (in pools and in real liquid)',
      'Render Distance bar in Settings, 1 to 10 (Ultra = everything); far water, liquid, lights and effects rest to save FPS',
      'Plus everything from Glass Lagoon and Tidal Engine below: real GPU liquid, reflections, caustics and more',
    ],
  },
  {
    id: 'glass-lagoon', name: 'Glass Lagoon', version: '0.6.1', time: 1790792629, tag: 'Engine',
    summary: 'Water you can see the bottom of. It mirrors the world around it and catches the sunlight.',
    items: [
      'Drops stretch into flat shapes along the surface, so a calm pool really looks calm',
      'The pool floor stays sharp through the water instead of looking shattered',
      'Reflections of the scene: walls, towers and players show up in the water (Water Quality Medium and up)',
      'Water sits in the shade of things that block the sun',
      'Caustics: bright wobbly lines of sunlight dance on the bottom of pools',
      'No more glittery sparkles on little ripples: the sun glint spreads out softly',
      'New Updates page on the website (this one!) that refreshes by itself',
    ],
  },
  {
    id: 'tidal-engine', name: 'Tidal Engine', version: '0.6.1', time: 1790786619, tag: 'Engine',
    summary: 'Real particle water that runs on your graphics card, and the Mega Water Slide to ride it.',
    items: [
      'Liquid simulated on the GPU: hundreds of thousands of drops at once',
      'FluidSystem and FluidEmitter for scripts, several liquids with their own colours, and a 100,000 drop limit that recycles the oldest drops',
      'Graphics API setting (Auto, or pick an OpenGL version) and a Water Quality setting',
      'Shadows fixed: no light leaking under boxes, and sharper shadows close to the camera',
      'Published games live on the server and show up on the website; saving in Studio updates them',
      'Faces are flat pictures painted on the head, not 3D shapes',
    ],
  },
  {
    id: 'bolts-and-bling', name: 'Bolts & Bling', version: '0.6.0', time: 1790768084, tag: 'Website',
    summary: 'Limiteds, trading, accessories and the Library. The biggest shopping update yet.',
    items: [
      'Limited items with numbered copies, resale and trading',
      'Accessories (hair, face, neck, shoulder, waist) made on a mannequin in Studio',
      'The Library: publish models publicly or privately, with pictures',
      '3D pictures in the catalog and a 3D view you can turn on item pages',
      'Game badges, game genres, votes and server cards on game pages',
      'Username changes for 1000 Bolts (your past names are kept)',
      'In-game menu, Shift Lock, player collisions and the Studio Assistant tab',
    ],
  },
  {
    id: 'eyes-on-the-prize', name: 'Eyes on the Prize', version: '0.5.3', time: 1790727423, tag: 'Player',
    summary: 'Look through your character\'s eyes, and watch other players move smoothly.',
    items: [
      'Scroll in to first person: the camera sits in the head and your character fades away',
      'Character hitboxes shaped like the classic ones, and walking that matches your speed',
      'Other players glide smoothly instead of jumping around',
      'Name tags above heads and /w for private whispers',
    ],
  },
  {
    id: 'making-waves', name: 'Making Waves', version: '0.5.3', time: 1790724793, tag: 'Engine',
    summary: 'Water that moves: waves, floating, splashes and water that pours and fills things up.',
    items: [
      'Waves, swell and currents; things float, and you splash when you jump in',
      'WaterSource pours water that spreads out, fills pools and overflows',
    ],
  },
  {
    id: 'monkey-bars-and-zombies', name: 'Monkey Bars & Zombies', version: '0.5.3', time: 1790723278, tag: 'Engine',
    summary: 'Climb, swim, build game menus, and get chased.',
    items: [
      'Climb trusses and ladders, and swim in water',
      'NPCs and zombies that find their way to you (PathfindingService)',
      'Game UI objects: ScreenGui, Frame, TextLabel, TextButton, ImageLabel',
    ],
  },
  {
    id: 'brickyard-2011', name: 'Brickyard 2011', version: '0.5.3', time: 1790700896, tag: 'Website',
    summary: 'The website and the Player go back to the good old days.',
    items: [
      'The website gets its 2011 look',
      'A "Connecting to server" screen like the old days',
      'Choose Your Character for guests, a new default face',
      'Configure your games on the website: name, pictures, who can play',
      'Email, forgot password and two-step verification',
      'Phones: the Android app fits the screen properly',
    ],
  },
  {
    id: 'puppet-strings', name: 'Puppet Strings', version: '0.5.2', time: 1790687355, tag: 'Studio',
    summary: 'Animate anything, and show off your avatar in 3D.',
    items: [
      'Animation Editor in Studio, and AnimationTracks for scripts',
      '3D avatars on the website, and profiles with what you\'re wearing',
      'Guests can play without an account',
      'Studio: F zooms to what you picked, rotate snap, and a grid that follows the snap',
    ],
  },
  {
    id: 'handshake-hotfix', name: 'Handshake Hotfix', version: '0.5.1', time: 1790682884, tag: 'Fix',
    summary: 'Fixed "SSL - Internal error" when connecting to the server.',
    items: [
      'Secure connections work again on every computer',
      'Footstep sounds while running',
    ],
  },
  {
    id: 'cloud-nine', name: 'Cloud Nine', version: '0.5.0', time: 1790650741, tag: 'Server',
    summary: 'Guts&Bolts moves into the cloud: always online, no one\'s PC needed.',
    items: [
      'The Guts&Bolts server runs on Cloudflare',
      'Sign up, log in and use the site in any browser',
      'Create page: My Games, decals, audio, clothes and plugins',
    ],
  },
  {
    id: 'stickers-and-skyline', name: 'Stickers & Skyline', version: '0.4.x', time: 1790645224, tag: 'Website',
    summary: 'Pictures on parts, and a real website to download from.',
    items: [
      'Decals: stick a picture on any side of a part',
      'The Guts&Bolts website with screenshots and downloads',
    ],
  },
  {
    id: 'toolbelt-and-trophies', name: 'Toolbelt & Trophies', version: '0.4.x', time: 1790643266, tag: 'Engine',
    summary: 'Tools to hold, scores to keep and places to save your progress.',
    items: [
      'Tools and a hotbar',
      'Leaderboards (leaderstats), checkpoints and DataStoreService',
      'Recorded jump, spawn and respawn sounds',
    ],
  },
];
